fundoo_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view
from django.views.generic.base import TemplateView
from fundoonote import views
from rest_framework import routers
#
app_name = 'fundoonote'
#
# router = routers.DefaultRouter()
# router.register(r'search', views.NotesDocumentViewSet, basename='search')
#

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^index/$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^fundoonote/', include('fundoonote.urls')),
    path('fundoonote/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

    # register
    url(r'^register/$', views.RegisterView.as_view(), name='register'),

    # forget page
    url(r'^forgot/$', views.Forgot.as_view(), name='forgot'),

    # login page
    url(r'^login/$', views.user_login, name='login'),

    # logout page
    url(r'^logout/$', views.user_logout, name='logout'),

    # To activate
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),

    # For social login
    url(r'^oauth/', include('social_django.urls', namespace='social')),

    # Swagger
    url(r'^swagger/', get_swagger_view(title="API Docs"), name="Docs"),

    # get all notes
    path('notes/', views.NoteView.as_view(), name='notes'),
    path('notesview/<int:id>/', views.NoteDetailView.as_view(), name='notesview'),

    # get archive notes
    path('archive/', views.ArchiveGetNotes.as_view(), name='archive'),
    path('archive/<int:id>/', views.ArchieveNote.as_view(), name='archive'),

    # get unarchive notes
    path('unarchive/', views.UnArchiveGetNotes.as_view(), name='unarchive'),
    path('unarchive/<int:id>/', views.UnArchieveNote.as_view(), name='unarchive'),

    # get reminder
    path('reminder/<int:id>/', views.SetReminder.as_view(), name='reminder'),
    path('reminder/', views.ReminderView.as_view(), name='reminder'),

    # get pin notes
    path('pin/<int:id>/', views.pinNote.as_view(), name='pin'),
    path('pin/', views.PinnedNotes.as_view(), name='pin'),
    # path('pin1/', views.PinGetNotes.as_view(), name='pin'),

    # get unpin notes
    path('unpin/<int:id>/', views.UnpinNote.as_view(), name='unpin'),
    path('unpin/', views.UnPinGetNotes.as_view(), name='unpin'),

    # trash notes
    path('trash/', views.TrashView.as_view(), name='trash'),

    # get all labels
    path('label/', views.LabelView.as_view(), name='label'),
    path('labels/<int:id>/', views.LabelDetailView.as_view(), name='labels'),

    # add n delete labels
    path('addlabel/<int:id>/', views.Addlabels.as_view(), name='addlabel'),
    path('deletelabel/<int:id>/', views.DeleteLabel.as_view(), name='deletelabel'),

    # image upload
    path('s3upload/', views.awss3, name='s3upload'),
    path('image_upload/', views.s3_upload, name='image_upload'),

    # collaborator
    path('collaborator/<int:id>/', views.Notecollaborator.as_view(), name='collaborator'),
    # path('deletecollaborator/<int:id>/', views.DeleteCollaborator.as_view(), name='deletecollaborator'),
    path('deletecollab/<int:id>/', views.Collaborator.as_view(), name='deletecollab'),

    # get all user through email id
    path('user_email/', views.getAllUser.as_view(), name='user'),

    path('collaborator1/<int:id>/', views.AddCollab.as_view(), name='collaborator1'),
    # url('', include(router.urls)),
]

fundoonote/urls.py
from django.conf.urls import url
from django.urls import include, path
from fundoonote import views


app_name = 'fundoonote'

urlpatterns = [
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('archieve/', views.ArchieveNote.as_view(), name='archieve'),
    path('pin/', views.pinNote.as_view(), name='pin'),


]

fundoonote/forms.py
from .models import UserProfileInfo
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# User form
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email')


class UserProfileInfoForm(forms.ModelForm):

    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

fundoonote/views.py
import json
import os
import pickle
import redis
from boto3.s3.transfer import S3Transfer
import logging
import self as self
from django.utils.decorators import method_decorator
# from .documents import NotesDocument
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import jwt
from .service import redis_methods
from .decorators import my_login_required
from rest_framework import status, serializers
from .models import Notes, Labels
from .serializers import NoteSerializer, RegisterSerializer
from .serializers import LabelSerializer
from django.views.decorators.csrf import csrf_exempt
from rest_framework.views import APIView
import boto3
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from django_elasticsearch_dsl_drf.constants import (
    LOOKUP_FILTER_RANGE,
    LOOKUP_QUERY_IN,
    LOOKUP_QUERY_GT,
    LOOKUP_QUERY_GTE,
    LOOKUP_QUERY_LT,
    LOOKUP_QUERY_LTE,
)
from django_elasticsearch_dsl_drf.filter_backends import (
    FilteringFilterBackend,
    OrderingFilterBackend,
    DefaultOrderingFilterBackend,
    CompoundSearchFilterBackend, FunctionalSuggesterFilterBackend)
from django_elasticsearch_dsl_drf.viewsets import DocumentViewSet
from .models import Account
from fundoonote.services.Service import Service
debug_logger = logging.getLogger('debug_logger')
error_logger = logging.getLogger('error_logger')
logger = logging.getLogger(__name__)


def index(request):
    return render(request, 'fundoonote/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    redis_methods.flush(self)
    return HttpResponseRedirect(reverse('index'))

@csrf_exempt
def user_login(request):
    # print(request.data)
    request_data = json.loads((request.body).decode('utf-8'))
    print(request_data)
    if request.method == 'POST':
        # username = request.POST.get('username')
        username = request_data['username']
        # password = request.POST.get('password')
        password = request_data['password']
        # authenticate the user n password
        user = authenticate(username=username, password=password)
        # check if user details is valid or not
        debug_logger.debug("Validating Data")
        if user:
            if user.is_active:
                payload = {
                    'id': user.id,
                    'email': user.email,
                }
                # it will create a token
                jwt_token = jwt.encode(payload, 'secret', 'HS256').decode('utf-8')
                print("abc", jwt_token)
                redis_methods.set_token(self, 'token', jwt_token)
                restoken = redis_methods.get_token(self, 'token')
                print("token in redis", restoken)
                login(request, user)
                debug_logger.debug("Validating Error")
                message = "you have successfully logged in"
                res = message
                result = {
                        'message': res,
                        'username': user.username,
                        'password': user.password,
                        'email': user.email,
                        'first_name': user.firstname,
                        'last_name': user.lastname,
                        'jwt_token': jwt_token
                }
                print(result)
                return JsonResponse({'result': result})
                # decode_jwt_token
            else:
                error_logger.error("Account Inactive Error")
                message = "Your account was inactive."
                status_code = 400
                return JsonResponse({'message': message, 'status': status_code})
        else:
            error_logger.error("Login Failed")
            print("They used username: {} and password: {}".format(username, password))
            message = "Invalid login details given"
            status_code = 400
            return JsonResponse({'message': message, 'status': status_code})
    else:
        return render(request, 'fundoonote/login.html', {})


class RegisterView(APIView):
    serializer_class = RegisterSerializer
    @csrf_exempt
    def post(self, request):
        redis = redis_methods()
        serializer = RegisterSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            debug_logger.debug("Validating Data..")
            if user:
                # get the current site url
                current_site = get_current_site(request)
                # create the email subject
                mail_subject = "Activate Your Account"
                # create the email body with activation link
                message = render_to_string("acc_active_email.html", {
                                            'user': user,  # pass the user
                                            'domain': current_site.domain,  # pass the current domail
                                            'uid': urlsafe_base64_encode(force_bytes(user.pk)),  # pass the uid in byte format
                                            'token': account_activation_token.make_token(user)  # pass the token
                                        })
                to_email = serializer.validated_data.get('email')  # get the user email
                email = EmailMessage(mail_subject, message, to=[to_email])
                email.send()  # send the mail for activation account
                return Response(serializer.data, status=status.HTTP_201_CREATED)
        error_logger.error("Not Valid data..")
        return Response(serializer.errors)


@csrf_exempt
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
        print(user)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
    debug_logger.debug("Validating Data")
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        error_logger.error("Invalid link..")
        return HttpResponse('Activation link is invalid!')


class Forgot(APIView):
    @csrf_exempt
    def post(self, request):
        email = request.data.get('email')
        print(email)
        domain = "localhost:3000/confirm"
        debug_logger.debug("Validating data")
        if email:
            user = Account.objects.get(email=email)
            current_site = get_current_site(request)
            mail_subject = "Reset your password"
            # create the email body with activation link
            message = render_to_string("acc_active_email.html", {
                'user': user,  # pass the user
                'domain': 'localhost:3000/resetpassword',  # pass the current domail
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),  # pass the uid in byte format
                'token': account_activation_token.make_token(user)  # pass the token
                })
            to_email = email
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()  # send the mail for activation account
            # return message
            return HttpResponse('Please confirm your email address to complete the registration')
        else:
            error_logger.error("Failed")
            return HttpResponse({"abc": "Fail"})


@csrf_exempt
def forgot_pass_activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
    debug_logger.debug("Validating Data")
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can reset your password:')
    else:
        error_logger.error("Account Inactive Error")
        return HttpResponse('Activation link is invalid!')


@csrf_exempt
def confirm(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
        print(user)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
    debug_logger.debug("Validating Data")
    if user is not None and account_activation_token.check_token(user, token):
        user.setpassword = True
        user.save()
        return HttpResponse('Password reset:')
    else:
        error_logger.error("Reset password is not send")
        return HttpResponse('Error in password reset')



@login_required
def home(request):
    return render(request, 'fundoonote/home.html')


# to create a note
class NoteView(APIView):
    serializer_class = NoteSerializer
    permission_classes = [AllowAny]

    @method_decorator(my_login_required)
    def get(self, request):

fundoonote/templates/fundoonote/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'register' %}">Register</a></li>
          <li><a class="navbar-link" href="{% url 'password_reset' %}">Forget Password</a></li>
          <li><a class="navbar-link" href="{% url 'notes' %}">CRUD</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'fundoonote:user_login' %}">Login</a></li>

          {% endif %}
</ul>
</div>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

fundoonote/templates/fundoonote/index.html
{% extends "fundoonote/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
      <body bgcolor="gray">
    <h1>Welcome to the Fundoo App !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Sign up or Login if you'd like to</h2>
    {% endif %}
      </body>
  </div>
</div>

{% endblock %}

fundoonote/templates/fundoonote/login.html
{% block body_block %}
    <div>
            <h1>Login Here !</h1>
            <form method="post" action="{% url 'fundoonote:user_login' %}">
                {% csrf_token %}
                {# A more "HTML" way of creating the login form#}
                <label for="username">Username:</label>
                <input type="text" name="username" placeholder="Username" required><br><br>
                <label for="password">Password:</label>
                <input type="password" name="password" placeholder="Password" required><br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="submit" name="" value="Login">
                <p><strong>-- OR --</strong></p>
                <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>
                 <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
            </form>
    </div>
{% endblock %}

fundoonote/templates/fundoonote/registration.html
{% extends "fundoonote/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
        {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

fundoonote/templates/fundoonote/signup.html
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="display: black">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: black">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}